import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Theme, ThemeOptions } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeProps: ThemeOptions = {
  // https://github.com/vercel/next.js/discussions/22388#discussioncomment-7282793
  appearance: "inherit",
  accentColor: "blue",
  grayColor: "gray",
  panelBackground: "solid",
  radius: "medium",
  scaling: "100%",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme {...themeProps}>
          <div className="p-5">{children}</div>
        </Theme>
      </body>
    </html>
  );
}
